//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tld15Server.Frontend.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tld15Server.Frontend.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        internal static string Account_ApiKey {
            get {
                return ResourceManager.GetString("Account.ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the new key now: it is hidden once you save, and it only starts working after you save..
        /// </summary>
        internal static string Account_ApiKey_CopyNow {
            get {
                return ResourceManager.GetString("Account.ApiKey.CopyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Account_ApiKey_Created {
            get {
                return ResourceManager.GetString("Account.ApiKey.Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last used.
        /// </summary>
        internal static string Account_ApiKey_LastUsed {
            get {
                return ResourceManager.GetString("Account.ApiKey.LastUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to never used.
        /// </summary>
        internal static string Account_ApiKey_NeverUsed {
            get {
                return ResourceManager.GetString("Account.ApiKey.NeverUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this account?.
        /// </summary>
        internal static string Account_ConfirmDelete {
            get {
                return ResourceManager.GetString("Account.ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string Account_Features {
            get {
                return ResourceManager.GetString("Account.Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Account_Login {
            get {
                return ResourceManager.GetString("Account.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Account_Password {
            get {
                return ResourceManager.GetString("Account.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string Account_Password_Current {
            get {
                return ResourceManager.GetString("Account.Password.Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string Account_Password_New {
            get {
                return ResourceManager.GetString("Account.Password.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Account_Status {
            get {
                return ResourceManager.GetString("Account.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Account_Type {
            get {
                return ResourceManager.GetString("Account.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        internal static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        internal static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fireplace of Despair.
        /// </summary>
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fireplace of Despair.
        /// </summary>
        internal static string Brand_Company {
            get {
                return ResourceManager.GetString("Brand.Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffering builds.
        /// </summary>
        internal static string Brand_Slogan {
            get {
                return ResourceManager.GetString("Brand.Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Common_Create {
            get {
                return ResourceManager.GetString("Common.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created At.
        /// </summary>
        internal static string Common_CreatedAt {
            get {
                return ResourceManager.GetString("Common.CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy/MM/dd HH:mm:ss.
        /// </summary>
        internal static string Common_DateTimeLong {
            get {
                return ResourceManager.GetString("Common.DateTimeLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Common_Delete {
            get {
                return ResourceManager.GetString("Common.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire At.
        /// </summary>
        internal static string Common_ExpireAt {
            get {
                return ResourceManager.GetString("Common.ExpireAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        internal static string Common_IP {
            get {
                return ResourceManager.GetString("Common.IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string Common_Main {
            get {
                return ResourceManager.GetString("Common.Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string Common_Manage {
            get {
                return ResourceManager.GetString("Common.Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Common_No {
            get {
                return ResourceManager.GetString("Common.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404.
        /// </summary>
        internal static string Common_NotFound {
            get {
                return ResourceManager.GetString("Common.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing was found.
        /// </summary>
        internal static string Common_NothingWasFound {
            get {
                return ResourceManager.GetString("Common.NothingWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reload the page..
        /// </summary>
        internal static string Common_ReloadPage {
            get {
                return ResourceManager.GetString("Common.ReloadPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string Common_Resume {
            get {
                return ResourceManager.GetString("Common.Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Common_Retry {
            get {
                return ResourceManager.GetString("Common.Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Common_Save {
            get {
                return ResourceManager.GetString("Common.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Common_Search {
            get {
                return ResourceManager.GetString("Common.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code.
        /// </summary>
        internal static string Common_SourceCode {
            get {
                return ResourceManager.GetString("Common.SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying again in {0} seconds.
        /// </summary>
        internal static string Common_TryingAgainIn {
            get {
                return ResourceManager.GetString("Common.TryingAgainIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Common_Update {
            get {
                return ResourceManager.GetString("Common.Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated At.
        /// </summary>
        internal static string Common_UpdatedAt {
            get {
                return ResourceManager.GetString("Common.UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agent.
        /// </summary>
        internal static string Common_UserAgent {
            get {
                return ResourceManager.GetString("Common.UserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Common_Version {
            get {
                return ResourceManager.GetString("Common.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Common_Yes {
            get {
                return ResourceManager.GetString("Common.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        internal static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string Identity_DoLogin {
            get {
                return ResourceManager.GetString("Identity.DoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident.
        /// </summary>
        internal static string Incident {
            get {
                return ResourceManager.GetString("Incident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not restore task assigned to the project.
        /// </summary>
        internal static string Incident_BusinessCannotRestoreIssueInProject {
            get {
                return ResourceManager.GetString("Incident.BusinessCannotRestoreIssueInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Forbidden.
        /// </summary>
        internal static string Incident_Forbidden {
            get {
                return ResourceManager.GetString("Incident.Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Error.
        /// </summary>
        internal static string Incident_General {
            get {
                return ResourceManager.GetString("Incident.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record was not found.
        /// </summary>
        internal static string Incident_NotFound {
            get {
                return ResourceManager.GetString("Incident.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page was not found..
        /// </summary>
        internal static string Incident_NotFoundPage {
            get {
                return ResourceManager.GetString("Incident.NotFoundPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many sign-in attempts. Try again later..
        /// </summary>
        internal static string Incident_TooManyAttempts {
            get {
                return ResourceManager.GetString("Incident.TooManyAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        internal static string Incident_Unauthorized {
            get {
                return ResourceManager.GetString("Incident.Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Failed.
        /// </summary>
        internal static string Incident_Validation {
            get {
                return ResourceManager.GetString("Incident.Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Mismatch.
        /// </summary>
        internal static string Incident_VersionMismatch {
            get {
                return ResourceManager.GetString("Incident.VersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong login or password.
        /// </summary>
        internal static string Incident_WrongPassword {
            get {
                return ResourceManager.GetString("Incident.WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        internal static string Issue {
            get {
                return ResourceManager.GetString("Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Issue_Category {
            get {
                return ResourceManager.GetString("Issue.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this issue?.
        /// </summary>
        internal static string Issue_ConfirmDelete {
            get {
                return ResourceManager.GetString("Issue.ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        internal static string Issue_Deadline {
            get {
                return ResourceManager.GetString("Issue.Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Issue_Done {
            get {
                return ResourceManager.GetString("Issue.Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Done.
        /// </summary>
        internal static string Issue_IsDone {
            get {
                return ResourceManager.GetString("Issue.IsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Top Priority.
        /// </summary>
        internal static string Issue_IsTopPriority {
            get {
                return ResourceManager.GetString("Issue.IsTopPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Issue_Name {
            get {
                return ResourceManager.GetString("Issue.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Issue_Note {
            get {
                return ResourceManager.GetString("Issue.Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Issue_Project {
            get {
                return ResourceManager.GetString("Issue.Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Project.
        /// </summary>
        internal static string Issue_Project_SelectProject {
            get {
                return ResourceManager.GetString("Issue.Project.SelectProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string Menu_System {
            get {
                return ResourceManager.GetString("Menu.System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string Pagination_First {
            get {
                return ResourceManager.GetString("Pagination.First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Pagination_Last {
            get {
                return ResourceManager.GetString("Pagination.Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Pagination_Next {
            get {
                return ResourceManager.GetString("Pagination.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Pagination_Previous {
            get {
                return ResourceManager.GetString("Pagination.Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this project?.
        /// </summary>
        internal static string Project_ConfirmDelete {
            get {
                return ResourceManager.GetString("Project.ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore in categories.
        /// </summary>
        internal static string Project_IgnoreInCategories {
            get {
                return ResourceManager.GetString("Project.IgnoreInCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Project_Name {
            get {
                return ResourceManager.GetString("Project.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string Project_Weight {
            get {
                return ResourceManager.GetString("Project.Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejoin failed..
        /// </summary>
        internal static string Reconnect_RejoinFailed {
            get {
                return ResourceManager.GetString("Reconnect.RejoinFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejoining the server..
        /// </summary>
        internal static string Reconnect_Rejoining {
            get {
                return ResourceManager.GetString("Reconnect.Rejoining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please retry or reload the page..
        /// </summary>
        internal static string Reconnect_RetryReload {
            get {
                return ResourceManager.GetString("Reconnect.RetryReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session has been paused by the server..
        /// </summary>
        internal static string Reconnect_SessionPaused {
            get {
                return ResourceManager.GetString("Reconnect.SessionPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to resume the session..
        /// </summary>
        internal static string Reconnnect_Failed {
            get {
                return ResourceManager.GetString("Reconnnect.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        internal static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this session?.
        /// </summary>
        internal static string Sessions_ConfirmDelete {
            get {
                return ResourceManager.GetString("Sessions.ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shevtsov &quot;Chief&quot; Stan.
        /// </summary>
        internal static string System_Author {
            get {
                return ResourceManager.GetString("System.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stan.
        /// </summary>
        internal static string System_Keywords {
            get {
                return ResourceManager.GetString("System.Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string System_Language {
            get {
                return ResourceManager.GetString("System.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
