// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// SPDX-License-Identifier: MPL-2.0
// SPDX-FileCopyrightText: 2025-2026 Shevtsov Stanislav (Fireplace of Despair)

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace StainlessGenerators;

/// <summary>
/// Writes the list of features and the list of endpoints at compile time.
/// </summary>
/// <remarks>
/// The startup used to reflect over the assembly to find them. Reflection reads nothing that the
/// compiler cannot read, and it costs the start-up a scan, hides a missing member until run time, and
/// keeps the assembly out of reach of the trimmer.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class RegistryGenerator : IIncrementalGenerator
{
    private const string FeatureInterface = "StainlessCore.Features.IFeature";
    private const string PublicEndpoint = "StainlessCore.Endpoints.IEndpointPublic";
    private const string ProtectedEndpoint = "StainlessCore.Endpoints.IEndpointProtected";
    private const string ExternalEndpoint = "StainlessCore.Endpoints.IEndpointExternal";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var types = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax declaration && declaration.BaseList != null,
                static (syntax, ctn) => syntax.SemanticModel.GetDeclaredSymbol(syntax.Node, ctn) as INamedTypeSymbol)
            .Where(static symbol => symbol != null)
            .Select(static (symbol, _) => symbol!)
            .Collect();

        context.RegisterSourceOutput(types, static (production, symbols) => Emit(production, symbols));
    }

    private static void Emit(SourceProductionContext production, ImmutableArray<INamedTypeSymbol> symbols)
    {
        var features = Select(symbols, FeatureInterface);
        var publicEndpoints = Select(symbols, PublicEndpoint);
        var protectedEndpoints = Select(symbols, ProtectedEndpoint);
        var externalEndpoints = Select(symbols, ExternalEndpoint);

        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace StainlessGenerated;");
        builder.AppendLine();
        builder.AppendLine("/// <summary> Features and endpoints of this assembly, found at compile time. </summary>");
        builder.AppendLine("internal static class Registry");
        builder.AppendLine("{");

        builder.AppendLine("    /// <summary> Identifier of every feature. One authorization policy belongs to each. </summary>");
        builder.AppendLine("    internal static readonly string[] FeatureIds = new string[]");
        builder.AppendLine("    {");
        foreach (var feature in features)
        {
            builder.Append("        ").Append(feature).AppendLine(".FeatureId,");
        }
        builder.AppendLine("    };");

        AppendMapper(builder, "MapPublic", publicEndpoints);
        AppendMapper(builder, "MapProtected", protectedEndpoints);
        AppendMapper(builder, "MapExternal", externalEndpoints);

        builder.AppendLine("}");

        production.AddSource("StainlessGenerated.Registry.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static void AppendMapper(StringBuilder builder, string name, List<string> endpoints)
    {
        builder.AppendLine();
        builder.AppendLine("    /// <summary> Map every endpoint of this area into the route group. </summary>");
        builder.Append("    internal static void ").Append(name)
               .AppendLine("(global::Microsoft.AspNetCore.Routing.RouteGroupBuilder apiGroup)");
        builder.AppendLine("    {");
        foreach (var endpoint in endpoints)
        {
            builder.Append("        ").Append(endpoint).AppendLine(".ConfigureRouting(apiGroup);");
        }
        builder.AppendLine("    }");
    }

    /// <summary> Names of the types that carry one interface, in a stable order. </summary>
    private static List<string> Select(ImmutableArray<INamedTypeSymbol> symbols, string interfaceName)
    {
        return symbols
            .Where(symbol => symbol.AllInterfaces.Any(carried => carried.ToDisplayString() == interfaceName))
            .Select(symbol => symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .Distinct()
            .OrderBy(name => name, System.StringComparer.Ordinal)
            .ToList();
    }
}
